version: '3'

services:
  cassandra1:
    image: cassandra:latest
    container_name: cassandra_db_server_container1
    ports:
      - "9042:9042"
    environment:
      - CASSANDRA_SEEDS=cassandra1,cassandra2,cassandra3
    networks:
      - cassandra-network
  cassandra2:
    image: cassandra:latest
    container_name: cassandra_db_server_container2
    environment:
      - CASSANDRA_SEEDS=cassandra1,cassandra2,cassandra3
    networks:
      - cassandra-network
  cassandra3:
    image: cassandra:latest
    container_name: cassandra_db_server_container3
    environment:
      - CASSANDRA_SEEDS=cassandra1,cassandra2,cassandra3
    networks:
      - cassandra-network

networks:
  cassandra-network:
    driver: bridge​
